### DISCUSSION TITLE
COnfigure kafka-ui to support SASL_SSL connnection to a secured Kafka

### DISCUSSION THREAD

**Discussion by nleeuskadi** [kafbat/kafka-ui#1002] [General]
Hello,

In the Kafka-ui documentation , I cannot find out how to set Kafka-ui helm chart values in order to make it configured in order to
connect to a secured Kafka through SALS_SSL.

Here below is a typical client.properties we are using to allow Clients to connect a secured kafka:

```
security.protocol=SASL_SSL
ssl.truststore.location=/path/to/truststore.p12
ssl.truststore.password="<<pwd>>"
ssl.truststore.type=PKCS12
sasl.mechanism=OAUTHBEARER
sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
  oauth.client.id="client-id" \
  oauth.client.secret="client-secret" \
  oauth.ssl.truststore.location="/path/to/truststore.p12" \
  oauth.ssl.truststore.password="<<pwd>>" \
  oauth.ssl.truststore.type="PKCS12" \
  oauth.token.endpoint.uri="https://$SSO_HOST/realms/ns_name/protocol/openid-connect/token" ;
  sasl.login.callback.handler.class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
```

How to set these parameters in the helm chart values of kafka-ui?

Thank you in advance :)

**Comment by germanosin** [comment]
Hi, @nleeuskadi 

1. The Strimzi OAuth2 callback class is missing; you'll need to add it to the classpath.  
2. Pass the configuration similarly to what you described:  

You can pass these configurations in YAML format using this method: [[Helm Charts Quick Start](https://ui.docs.kafbat.io/configuration/helm-charts/quick-start#passing-configuration-file-as-configmap)](https://ui.docs.kafbat.io/configuration/helm-charts/quick-start#passing-configuration-file-as-configmap).  

```yaml
kafka:
  clusters:
    - name: Server
      properties:
        security.protocol: SASL_SSL
        ssl.truststore.location: /path/to/truststore.p12
        ssl.truststore.password: <<pwd>>
        ssl.truststore.type: PKCS12
        sasl.mechanism: OAUTHBEARER
        sasl.jaas.config: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required oauth.client.id="client-id" oauth.client.secret="client-secret" oauth.ssl.truststore.location="/path/to/truststore.p12" oauth.ssl.truststore.password="<<pwd>>" oauth.ssl.truststore.type="PKCS12" oauth.token.endpoint.uri="https://$SSO_HOST/realms/ns_name/protocol/openid-connect/token";
        sasl.login.callback.handler.class: io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
```
