### DISCUSSION TITLE
how to enable JumpCloud SSO with kafka-ui using Oauth2

### DISCUSSION THREAD

**Discussion by vagharsh** [kafbat/kafka-ui#1011] [Q&A]
i have tested almost all variants of configuration in kafka-ui and i am getting invalid credentials .
this is my current helm values.
```
yamlApplicationConfig:
  kafka:
    clusters:
      - name: dev
        bootstrapServers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  auth:
    type: OAUTH2
    oauth2:
      client:
        jumpcloud:
          clientId: XXXXXX
          clientSecret: XXXXXX
          scope:
            - email
            - openid
            - groups
          provider: jumpcloud
          client-name: jumpcloud
          issuer-uri: https://oauth.id.jumpcloud.com/
          redirect-uri: https://localhost:8080/login/oauth2/code/jumpcloud
          authorization-grant-type: authorization_code
          jwk-set-uri: https://oauth.id.jumpcloud.com/.well-known/jwks.json
          user-name-attribute: email
          custom-params:
            type: oauth
            roles-field: groups
  
  rbac:
    roles:
      - name: "admins"
        clusters:
          - dev
        subjects:
          - provider: oauth
            type: group
            value: "groups"
        permissions:
          - resource: applicationconfig
            actions: all

          - resource: clusterconfig
            actions: all

          - resource: topic
            value: ".*"
            actions: all

          - resource: consumer
            value: ".*"
            actions: all

          - resource: schema
            value: ".*"
            actions: all

          - resource: connect
            value: ".*"
            actions: all

          - resource: ksql
            actions: all

          - resource: acl
            actions: [ view, edit ]
  management:
    health:
      ldap:
        enabled: false

env:
  - name: JAVA_OPTS
    value: '-Dlogging.level.root=DEBUG'
```

**Comment by vagharsh** [comment]
https://github.com/provectus/kafka-ui/discussions/4527 for observability

**Comment by Haarolean** [comment]
add this:
```
logging:
  level:
    root: INFO
    io.kafbat.ui: DEBUG
    org.springframework.security: DEBUG
```

upon 'invalid credentials' grep logs by `AuthenticationWebFilter`, message should be like `Authentication failed: <reason>`

**Comment by vagharsh** [comment]
it says access denied in the logs.. 

what are the correct login, logout, redirect uri for kafkabat ?

**Reply by Haarolean** [reply]
A bunch of examples for different oidc providers: https://ui.docs.kafbat.io/configuration/authentication/oauth2
'access denied' is a misconfiguration on your oidc provider side. Check for scopes permissions, etc. Not familiar with that provider, can't help further, unfortunately

**Reply by xchoavagyan** [reply]
@Haarolean 

 Can you explain the difference between using auth and spring.security configurations in a Helm chart deployment?

Are both required, or can one be used without the other?

Specifically in the context of using a yaml.configurationFile block within a Helm chart.

Additionally, could you provide a full example using a generic OAuth provider setup, ideally showcasing best practices?

```auth:
  type: OAUTH2
  oauth2:
    client:
      <unique_name>:
        clientId: xxx
        clientSecret: yyy
        scope: openid
        client-name: cognito # will be displayed on the login page
        provider: <provider>
        redirect-uri: http://localhost:8080/login/oauth2/code/<provider>
        authorization-grant-type: authorization_code
        issuer-uri: https://xxx
        jwk-set-uri: https://yyy/.well-known/jwks.json
        user-name-attribute: <zzz>
        custom-params:
          type: <provider_type> # fill this if you're gonna use RBAC. Supported values: cognito, google, github, oauth 
          roles-field: groups # required for RBAC, a field name in OAuth token which will contain user's roles/groups
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          issuer-uri: http://localhost:8383/realms/foo```

**Reply by Haarolean** [reply]
the link above specifies the properties you need to use, there are no properties starting with `spring` there, where did you get that?

**Reply by xchoavagyan** [reply]
[  # spring helm configuration :](https://github.com/kafbat/helm-charts/blob/8b726c173217665f6d86e4a301f83ed006428ff1/charts/kafka-ui/values.yaml#L44)

**Reply by xchoavagyan** [reply]
@Haarolean Can you provide working values, with example, or which usage is correct, with `auth` or `spring`, also from where you get this , this is not exists in any documentation
```
logging:
  level:
    root: INFO
    io.kafbat.ui: DEBUG
    org.springframework.security: DEBUG
```

**Reply by Haarolean** [reply]
nope, that's outdated and commented out. Docs prevail

**Reply by xchoavagyan** [reply]
where I can find latest docs, or examples?

**Reply by vagharsh** [reply]
@Haarolean  after updating the values files to 
```
yamlApplicationConfig:
  kafka:
    clusters:
      - name: dev
        bootstrapServers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  logging:
    level:
      root: INFO
      io.kafbat.ui: DEBUG
      org.springframework.security: DEBUG
  auth:
    type: OAUTH2
    oauth2:
      client:
        jumpcloud:
          clientId: XXXXX
          clientSecret: XXXXX
          scope:
            - email
            - openid
            - groups
          provider: jumpcloud
          client-name: jumpcloud
          issuer-uri: https://oauth.id.jumpcloud.com/
          redirect-uri: https://localhost:8080/login/oauth2/code/jumpcloud
          authorization-grant-type: authorization_code
          token-endpoint-auth-method: client_secret_post
          jwk-set-uri: https://oauth.id.jumpcloud.com/.well-known/jwks.json
          user-name-attribute: email
          custom-params:
            type: oauth
            roles-field: groups
```
now i am getting another error
```
org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_client] Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). The OAuth 2.0 Client supports client authentication method 'client_secret_post', but method 'client_secret_basic' was requested. You must configure the OAuth 2.0 client's 'token_endpoint_auth_method' value to accept 'client_secret_basic'.
	at org.springframework.security.oauth2.client.oidc.authentication.OidcAuthorizationCodeReactiveAuthenticationManager.lambda$authenticate$2(OidcAuthorizationCodeReactiveAuthenticationManager.java:149)
	at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3848)
```
