### DISCUSSION TITLE
KafkaConnect Configuration

### DISCUSSION THREAD

**Discussion by stitch-marinus** [kafbat/kafka-ui#1037] [Q&A]
Hi,

I've managed to set Kafbat up and connect it Kafka and noticed support for KafkaConnect. At present my Kafka Connect cluster uses SCRAM-512 to connect to Kafka.

I have a config that looks something like this (for testing):
```yaml
yamlApplicationConfig:
  kafka:
    clusters:
      - name: my-cluster
        bootstrapServers: my-cluster-kafka-bootstrap:9093
        properties:
          ssl:
            truststore:
              location: /ssl/kafbat.truststore.jks
              password: "123456789"
          protocol: SASL
          sasl:
            mechanism: SCRAM-SHA-512
            jaas:
              config: org.apache.kafka.common.security.scram.ScramLoginModule required username="my-connect" password="<psswrd>";
          security:
            protocol: SASL_SSL
        kafkaConnect:
          - name: my-connect
            address: my-connect-connect:8083

volumeMounts:
 - name: config-volume
   mountPath: /ssl

volumes:
 - name: config-volume
   configMap:
     name: kafbat-ssl-files
```

I don't see the kafka connector pop up is there something missing (I don't have authentication set up on the test kafka connect cluster)?
