### DISCUSSION TITLE
Configure Schema Registry with kafka ui

### DISCUSSION THREAD

**Discussion by rajarshp** [kafbat/kafka-ui#1107] [Q&A] [answered]
Hello
We have configured Bitnami Schema Registry in our namespace(AWS Rosa) and want to use it in the Kafka ui. Can you please let me know how to use it ?

I added below part but it is not visible in the Kafka ui values file but still I cannot see it in the UI.

```
amlApplicationConfig:
  kafka:
    clusters:
      - name: ac-prime-kafka
        bootstrapServers: kafka-bootstrap.<DNS>:443
        schemaRegistry: 
          url: http://schema-registry.<NAMESPACE>.svc.cluster.local:8081
```

![image](https://github.com/user-attachments/assets/79d292ba-ca09-4cdd-8401-2bb86f1d7277)

**Update:**
I guess it took time to display the icon, but now when I am trying to access Schema Registry it is giving 500 error. IN the log I can see an error like host not defined or unable to connect schema-registry.<NAMESPACE>.svc.cluster.local:8081

how to resolve this

**Comment by Haarolean** [comment]
>host not defined or unable to connect schema-registry..svc.cluster.local:8081
this is a networking issue, make sure the pod is reacheable from k-ui

**Comment by germanosin** [comment, marked as answer]
@rajarshp 
config should look like:
```
amlApplicationConfig:
  kafka:
    clusters:
      - name: ac-prime-kafka
        bootstrapServers: kafka-bootstrap.<DNS>:443
        schemaRegistry: http://schema-registry.<NAMESPACE>.svc.cluster.local:8081
```          
You could check possible config values here: https://ui.docs.kafbat.io/configuration/configuration-file
