### DISCUSSION TITLE
Azure SSO and RBAC and Helm

### DISCUSSION THREAD

**Discussion by dimashenkov** [kafbat/kafka-ui#290] [Q&A] [answered]
Im trying this configuration for RBAC and Azure but its not working , I can login with admin role but cant see my cluster in the UI. Is this the right way ?
```
yamlApplicationConfig:
   auth:
      type: OAUTH2
      oauth2:
        client:
          azure:
            provider: azure
            clientId: 2******
            clientSecret: *******
            scope: "openid"
            clientName: "azure"
            redirect-uri: https://kafka-ui.dev.product.frankfurt.bla.cloud/login/oauth2/code/azure
            issuerUri: "https://login.microsoftonline.com/707*******/v2.0"
            user-name-attribute: name
            custom-params:
              type: oauth #must be 'oauth'
              roles-field: roles # roles claim contains all granted roles for a user
    
  rbac:
    roles:
      - name: "admin"
        clusters:
          - kafka-cluster-dev
        subjects:
          - provider: oauth  # Added your Azure provider
            type: user
            value: "smit.sth@bla.org"  # Your email as admin        
          - provider: oauth  # Added your Azure provider
            type: user
            value: "john.do@bla.org"  # Your email as admin
        permissions:
          - resource: clusterconfig
            actions: all
          - resource: topic
            value: ".*"
            actions: [ "view", "create", "edit", "delete", "messages_produce" ]
          - resource: consumer
            value: ".*"
            actions: all
          - resource: schema
            value: ".*"
            actions: all
          - resource: connect
            value: ".*"
            actions: all
          - resource: ksql
            actions: all
      - name: "readonly"
        clusters:
          - kafka-cluster-dev
        subjects:
          - provider: oauth
            type: domain
            value: "bla.org"
        permissions:
          - resource: clusterconfig
            actions: [ "view" ]
          - resource: topic
            value: ".*"
            actions: [ "view" ]
          - resource: consumer
            value: ".*"
            actions: [ "view" ]
          - resource: schema
            value: ".*"
            actions: [ "view" ]
          - resource: connect
            value: ".*"
            actions: [ "view" ] 
```

**Comment by Haarolean** [comment]
Hi, yes, your config looks valid. The issue might be that the field you're looking for (roles) is either missing in your token or is empty.

You can debug this like that:

1. Add the following logging level:
```
yamlApplicationConfig:
  logging:
    level:
      io.kafbat.ui.service.rbac.extractor: TRACE
```
2. Restart the app, autenticate and grep logs for `OauthAuthorityExtractor`, this should help.

Let me know how it goes.

**Reply by Haarolean** [reply]
Ah, also, since you're trying to bind via username, it's important to correctly set the `user-name-attribute: name` value. If `name` field is missing in your token (or not email) it won't work. So please make sure it's an email indeed.

**Reply by dimashenkov** [reply]
name is not missing cuz I see it in the UI profile

**Reply by Haarolean** [reply]
@dimashenkov does the name in UI match the one in the config? It's case sensitive.

**Reply by dimashenkov** [reply]
yes it is matching

**Reply by Haarolean** [reply]
aight, I'll provide you an image to test things out today

**Reply by Haarolean** [reply]
@dimashenkov could you please try this image out?
https://github.com/kafbat/kafka-ui/pkgs/container/kafka-ui/203893596?tag=test_oauth
with the same logging property enabled you should observe something like the following:
```
2024-04-15 21:25:18,505 TRACE [reactor-http-nio-6] i.k.u.s.r.e.OauthAuthorityExtractor: Extracting OAuth2 user authorities
2024-04-15 21:25:43,818 DEBUG [reactor-http-nio-6] i.k.u.s.r.e.OauthAuthorityExtractor: Principal name is: [Haarolean]
2024-04-15 21:25:43,820 TRACE [reactor-http-nio-6] i.k.u.s.r.e.OauthAuthorityExtractor: [Haarolean] matches [Haarolean]? [true]
2024-04-15 21:25:43,820 DEBUG [reactor-http-nio-6] i.k.u.s.r.e.OauthAuthorityExtractor: Matched roles by username: [memelords]
2024-04-15 21:25:43,820 WARN  [reactor-http-nio-6] i.k.u.s.r.e.OauthAuthorityExtractor: Param missing in attributes, nothing to do
2024-04-15 21:25:43,820 DEBUG [reactor-http-nio-6] i.k.u.s.r.e.OauthAuthorityExtractor: Principal [Haarolean] doesn't have any roles, nothing to do
```

**Reply by dimashenkov** [reply]
2024-04-15 15:16:09,417 WARN  [boundedElastic-2] o.s.b.a.l.LdapHealthIndicator: LDAP health check failed
Caused by: javax.naming.CommunicationException: localhost:389

Readiness probe failed: Get "http://10.2.47.233:8080/actuator/health": dial tcp 10.2.47.233:8080: connect: connection refused

**Reply by Haarolean** [reply]
it's a warn, you can ignore that.

**Reply by dimashenkov** [reply]
Readiness probe failed is the problem , my chart cant start with this image

**Reply by Haarolean** [reply]
please disable the probes for now as this is a demo image

**Reply by dimashenkov** [reply]
Yes I see that, looks like the user doesnt have attached role .
```
2024-04-16 06:26:04,412 TRACE [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Extracting OAuth2 user authorities
2024-04-16 06:26:04,412 DEBUG [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Principal name is: [Smit Sth]matches [Smit Sth]? [false]
2024-04-16 06:26:04,413 TRACE [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: [smit.sth@bla.org] matches [SMit Sth]? [false]
2024-04-16 06:26:04,413 DEBUG [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Matched roles by username: []
2024-04-16 06:26:04,413 WARN  [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Param missing in attributes, nothing to do
2024-04-16 06:26:04,413 DEBUG [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Principal [Smit Sth] doesn't have any roles, nothing to do
```

**Comment by dimashenkov** [comment]
> Hi, yes, your config looks valid. The issue might be that the field you're looking for (roles) is either missing in your token or is empty.
> 
> You can debug this like that:
> 
> 1. Add the following logging level:
> 
> ```
> yamlApplicationConfig:
>   logging:
>     level:
>       io.kafbat.ui.service.rbac.extractor: TRACE
> ```
> 
> 2. Restart the app, autenticate and grep logs for `OauthAuthorityExtractor`, this should help.
> 
> Let me know how it goes.

nothing new comes up in the logs :( after this change

**Reply by Haarolean** [reply]
Yeah sorry there won't be anything since you're matching by the username

**Reply by dimashenkov** [reply]
good with user-name-attribute: email , admin role is working , but my readonly role is not. What should  I change?

**Reply by Haarolean** [reply]
@dimashenkov `provider: oauth` supports only two types of things: `user` and `role`.

**Reply by dimashenkov** [reply]
ok so I need to specify user by user for readonly ?

**Reply by Haarolean** [reply]
Depends on what's more convenient for you.
You can either match via user or a role.
Matching by the role will require the presence of the roles attribute for the user.

Also it sounds like a good use case to support regex values, so you could use "*@domain.tld" emails to match the roles without having to populate the users with roles. We could consider implementing such a feature if you don't mind raising a separate issue for this.

**Reply by dimashenkov** [reply]
Ok but it looks like this RBAC will not work with official latest image right , i need to stay with yours  #   tag: "test_oauth" ?

**Reply by Haarolean** [reply]
Yeah I've changed a thing there which affects you: currently if you don't have the roles field present no mapping will be done (even via username). I'll merge the changes soon, so you can switch to `main`-tagged image instead.

**Reply by dimashenkov** [reply]
thank you!

**Reply by dimashenkov** [reply]
pls comment here to let me know.

**Reply by prashanthm10** [reply]
@Haarolean  I am using the below configuration:
<img width="889" alt="image" src="https://github.com/kafbat/kafka-ui/assets/25369903/44f0261a-548e-4a2f-9b00-c38fad771363">
            
            
And I am getting the below from the logs
2024-04-24 09:47:19,877 TRACE [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Extracting OAuth2 user authorities
2024-04-24 09:47:19,877 DEBUG [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Principal name is: [Prashanth Muppalla]
2024-04-24 09:47:19,970 DEBUG [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Matched roles by username: []
2024-04-24 09:47:19,971 TRACE [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: The field is either a set or a list, returning as is
2024-04-24 09:47:19,972 DEBUG [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Token's groups: [admin]
2024-04-24 09:47:19,975 DEBUG [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Matched group roles: []
         
         
my Azure roles:
<img width="1046" alt="image" src="https://github.com/kafbat/kafka-ui/assets/25369903/d110af2f-f4ee-470b-8dd1-0e409e33e084">

can you point where the error is exactly? I don't see any clusters in the console after putting rbac

**Reply by Haarolean** [reply]
> @Haarolean  I am using the below configuration:
> 
> <img width="889" alt="image" src="https://github.com/kafbat/kafka-ui/assets/25369903/44f0261a-548e-4a2f-9b00-c38fad771363">
> 
>             
> 
>             
> 
> And I am getting the below from the logs
> 
> 2024-04-24 09:47:19,877 TRACE [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Extracting OAuth2 user authorities
> 
> 2024-04-24 09:47:19,877 DEBUG [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Principal name is: [Prashanth Muppalla]
> 
> 2024-04-24 09:47:19,970 DEBUG [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Matched roles by username: []
> 
> 2024-04-24 09:47:19,971 TRACE [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: The field is either a set or a list, returning as is
> 
> 2024-04-24 09:47:19,972 DEBUG [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Token's groups: [admin]
> 
> 2024-04-24 09:47:19,975 DEBUG [reactor-http-epoll-4] i.k.u.s.r.e.OauthAuthorityExtractor: Matched group roles: []
> 
>          
> 
>          
> 
> my Azure roles:
> 
> <img width="1046" alt="image" src="https://github.com/kafbat/kafka-ui/assets/25369903/d110af2f-f4ee-470b-8dd1-0e409e33e084">
> 
> 
> 
> can you point where the error is exactly? I don't see any clusters in the console after putting rbac

> value: "admin"

You don't need quotes in YAML unless the value contains special characters.

**Reply by prashanthm10** [reply]
still the same issue

**Reply by prashanthm10** [reply]
My config now:
<img width="433" alt="image" src="https://github.com/kafbat/kafka-ui/assets/25369903/4c06514e-bfdc-486c-bee1-7aa70a6bd046">

Corresponding logs:
<img width="1247" alt="image" src="https://github.com/kafbat/kafka-ui/assets/25369903/bc22d3d3-eab0-4417-b03d-7b63201a870f">

In Principal name I have removed my email id, just kept the username in the screenshot though I have used this 
user-name-attribute: email

**Reply by Haarolean** [reply]
> My config now:
> 
> <img width="433" alt="image" src="https://github.com/kafbat/kafka-ui/assets/25369903/4c06514e-bfdc-486c-bee1-7aa70a6bd046">
> 
> 
> 
> Corresponding logs:
> 
> <img width="1247" alt="image" src="https://github.com/kafbat/kafka-ui/assets/25369903/bc22d3d3-eab0-4417-b03d-7b63201a870f">
> 
> 
> 
> In Principal name I have removed my email id, just kept the username in the screenshot though I have used this 
> 
> user-name-attribute: email

It's `type: role`, not "roles"

**Reply by prashanthm10** [reply]
Thank you that works.

**Reply by prashanthm10** [reply]
Also please let us know when it's merged to main so that we can use the versioned tag. Thank you once again.

**Reply by prashanthm10** [reply]
@Haarolean when will "test_oauth" go into production. I am using helm charts to deploy this so waiting for the latest version of that.

**Reply by Haarolean** [reply]
@prashanthm10 it's available in "main"-tagged image

**Comment by Haarolean** [comment, marked as answer]
@dimashenkov 

Based on logs from https://github.com/kafbat/kafka-ui/discussions/290#discussioncomment-9125977:

"Principal name" in log is the value of the field `user-name-attribute`. We use that value to match the subjects in RBAC. 

This obviously doesn't work, as your email is not equal to your name.

I suggest either changing `user-name-attribute` to email field or specifying the username instead of email in RBAC config.

Please consider sponsoring our activities ([link](https://github.com/sponsors/kafbat)) if you appreciate the provided support.

**Comment by fedeostrit** [comment]
hi @Haarolean, I have authentication errors with OAuth and Azure, I enabled logging but I don't see anything in the authentication logs.
```
    logging:
      level:
        root: INFO
        io.kafbat.ui: DEBUG
        io.kafbat.ui.service.rbac.extractor: DEBUG
        reactor.netty.http.server.AccessLog: DEBUG
        org.hibernate.validator: WARN
```

my config:

 ```
auth:
      type: OAUTH2
      oauth2:
        client:
          azure:
            client-name: azure
            clientId: xxxxxxxx
            clientSecret: xxxxxx
            issuer-uri: https://login.microsoftonline.com/xxxxx/v2.0
            jwk-set-uri: https://login.microsoftonline.com/xxxxx/discovery/v2.0/keys
            provider: azure
            scope: openid
            user-name-attribute: name
            custom-params:
              type: oauth
              roles-field: roles
```
