### DISCUSSION TITLE
Param missing from attributes when login with oauth2

### DISCUSSION THREAD

**Discussion by marcosschroh** [kafbat/kafka-ui#333] [Q&A] [answered]
I am having a problem with `oauth2`. After the configuration I can properly login, the `rbac` works as expected only with `type: user` on `subjects` but does not with `type: role`. I can see in the logs these lines:

```bash
DEBUG [reactor-http-epoll-1] i.k.u.s.r.e.OauthAuthorityExtractor: Param missing from attributes, skipping
DEBUG [reactor-http-epoll-1] i.k.u.s.r.e.OauthAuthorityExtractor: Token's groups: []
DEBUG [reactor-http-epoll-1] i.k.u.s.r.e.OauthAuthorityExtractor: Matched roles: []
```

I think the config is correct:

```yaml
auth:
  type: OAUTH2
  oauth2:
    client:
      my-oauth:
        provider: my-oauth
        clientId: ...
        clientSecret: ...
        client-name: "my-oauth" # will be displayed on the login page
        redirect-uri: https://...
        authorization-grant-type: authorization_code
        issuer-uri: https://d...
        scope: ["openid", "groups", "userinfo"]
        custom-params:
          type: oauth
          roles-field: groups # required for RBAC, a field name in OAuth token which will contain user's roles/groups
```

Any ideas? Does `Param missing from attributes, skipping` mean that `groups` were not found in the response from the `oauth2` provider? Thanks
