### DISCUSSION TITLE
Cannot cast com.provectus.kafka.ui.config.auth.RbacOidcUser

### DISCUSSION THREAD

**Discussion by haroon9** [kafbat/kafka-ui#403] [Q&A] [answered]
I have configured the following RBAC with Azure OAUTH, and it is currently working, but there is an exception that appears in the pod logs whenever I load anything using the UI:

`ERROR [reactor-http-epoll-2] r.c.p.Operators: Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.ClassCastException: Cannot cast com.provectus.kafka.ui.config.auth.RbacOidcUser to org.springframework.security.core.userdetails.UserDetails
Caused by: java.lang.ClassCastException: Cannot cast com.provectus.kafka.ui.config.auth.RbacOidcUser to org.springframework.security.core.userdetails.UserDetails`

My current configurations:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-configmap
data:
  KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: "SSL"
  KAFKA_CLUSTERS_0_NAME: "kafka"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: {{ .Values.bootstrapServer | quote}}
  KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /var/cluster/ca.p12
  KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_TYPE: PKCS12
  KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /var/user/user.p12
  KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_TYPE: PKCS12
  AUTH_TYPE: "OAUTH2"
  AUTH_OAUTH2_CLIENT_AZURE_CLIENTID: {{ .Values.oauth.clientId | quote}}
  AUTH_OAUTH2_CLIENT_AZURE_CLIENTSECRET: {{ .Values.oauth.clientSecret | quote}}
  AUTH_OAUTH2_CLIENT_AZURE_SCOPE: "openid"
  AUTH_OAUTH2_CLIENT_AZURE_CLIENTNAME: "Kafka UI OAuth"
  AUTH_OAUTH2_CLIENT_AZURE_PROVIDER: "azure"
  AUTH_OAUTH2_CLIENT_AZURE_ISSUERURI: "https://login.microsoftonline.com/{{ .Values.oauth.tenantId }}/v2.0"
  AUTH_OAUTH2_CLIENT_AZURE_JWKSETURI: "https://login.microsoftonline.com/{{ .Values.oauth.tenantId }}/discovery/v2.0/keys"
  AUTH_OAUTH2_CLIENT_AZURE_USER-NAME-ATTRIBUTE: "name"
  AUTH_OAUTH2_CLIENT_AZURE_CUSTOM-PARAMS_TYPE: "oauth"
  AUTH_OAUTH2_CLIENT_AZURE_CUSTOM-PARAMS_ROLES-FIELD: "roles"
  LOGGING_LEVEL_COM.PROVECTUS.KAFKA.UI.SERVICE.RBAC.EXTRACTOR: TRACE
  SPRING_CONFIG_ADDITIONAL-LOCATION: /var/roles/roles.yaml
```

The RBAC:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-roles
data:
  roles.yaml: |-
    rbac:
      roles:
        - name: "admins"
          clusters:
            - local
            - kafka
          subjects:
            - provider: oauth
              type: role
              value: "Kafka.Use"
          permissions:
            - resource: applicationconfig
              actions: all
          
            - resource: clusterconfig
              actions: all

            - resource: topic
              value: ".*"
              actions: all

            - resource: consumer
              value: ".*"
              actions: all

            - resource: schema
              value: ".*"
              actions: all

            - resource: connect
              value: ".*"
              actions: all

            - resource: ksql
              actions: all
              
            - resource: acl
              value: ".*"
              actions: all
```

The role is `Kafka.Use`, which I created inside the client app `Kafka UI OAuth. ' Is there any config missing?
