### DISCUSSION TITLE
Setting logs to info

### DISCUSSION THREAD

**Discussion by DavidConnack** [kafbat/kafka-ui#436] [Q&A] [answered]
Pretty sure this is a simple thing, I had it working with the Provectus images.
Ive attempted to set the logs to info (why are they not info by default?) like this:
```yaml
yamlApplicationConfig:
  logging:
    level:
      io:
        kafbat: info
```

as well as:
```yaml
yamlApplicationConfig:
  logging:
    level:
      io.kafbat: info
```
but its still outputting debug logs.

**Comment by Haarolean** [comment, marked as answer]
Hi, it works for me (in non-helm env, at least):

```
logging:
  level:
    root: OFF
    io.kafbat.ui: WARN
```

Make sure your `yamlApplicationConfig` is forwarded into the container, you can verify this by setting root to OFF, for example.
