### DISCUSSION TITLE
LDAP Group Filter Issue While Evaluating Username

### DISCUSSION THREAD

**Discussion by lbzv9** [kafbat/kafka-ui#604] [Q&A]
Hi,

I have enabled LDAP authentication successfully but facing issues with group search filter when we pass {0}

below is config

```
- name: AUTH_TYPE
  value: "LDAP"
- name: SPRING_LDAP_URLS
  value: "ldap://corp.test.com:389"
- name: SPRING_LDAP_BASE
  value: "o=test.com,o=email"
- name: SPRING_LDAP_ADMIN_USER
  value: "uid=admin,ou=people,o=test.com,o=email"
- name: SPRING_LDAP_ADMIN_PASSWORD
  value: "<PWD>"
- name: SPRING_LDAP_USER_FILTER_SEARCH_BASE
  value: "ou=people,o=test.com,o=email"
- name: SPRING_LDAP_USER_FILTER_SEARCH_FILTER
  value: "(uid={0})"
- name: SPRING_LDAP_GROUP_FILTER_SEARCH_BASE
  value: "ou=Groups,o=test.com,o=email"
- name: SPRING_LDAP_GROUP_FILTER_SEARCH_FILTER
  value: "(uniqueMember=uid={0},ou=people,o=test.com,o=email)"
  ```

in roles.yaml,
```
          subjects:
            - provider: ldap
              type: group
              value: "group1"
```

I tried hardcoding username in the group search filter and it works.
```
- name: SPRING_LDAP_GROUP_FILTER_SEARCH_FILTER
   value: "(uniqueMember=uid=user1,ou=people,o=test.com,o=email)"
```

Checking to see what is missing here.

**Comment by Haarolean** [comment]
Hi, sorry for the delay.

Please try evaluating logs with trace enabled:
```
logging:
  level:
    io.kafbat.ui.service.rbac.extractor: TRACE
    org.springframework.security.ldap.userdetails: TRACE
```
