### DISCUSSION TITLE
Kafka UI Settings with SASL_SSL and OAUTHBEARER

### DISCUSSION THREAD

**Discussion by MariaIRubio** [kafbat/kafka-ui#857] [Q&A]
Hi! I am having problems to configure my broker in the UI with SASL_SSL y OAUTHBEARER mechanism. 
How should the sasl.jaas.config be?

Something like this?
```
org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required  oauth.client.id="clientid" oauth.client.secret="clientsecret" oauth.token.endpoint.uri="issuer/auth/realms/realm/protocol/openid-connect/token"; sasl.oauthbearer.sub.claim.name="preferred_username"; sasl.client.callback.handler.class="io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler";
```
like this?

```
KafkaClient {
	org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule Required 
	usecuredLoginStringClaim_sub="preferred_name";
};

```

like this?

```
KafkaClient{
org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required  
oauth.client.id="clientid" 
oauth.client.secret="clientsecret" 
oauth.token.endpoint.uri="issuer/auth/realms/realm/protocol/openid-connect/token";
sasl.oauthbearer.sub.claim.name="preferred_username"; 
sasl.client.callback.handler.class="io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler";
};
```

something totally different?

Thank you very much in advance

**Comment by Haarolean** [comment]
Here's an example with oauthbearer from someone on our discord:
https://discord.com/channels/897805035122077716/1308116619427582003/1311033339309854762
```
kafka:
  clusters:
    - name: local
      properties:
        sasl.mechanism: OAUTHBEARER
        security.protocol: SASL_PLAINTEXT
        jaas.config: 'org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required oauth.client.id="client-id" oauth.client.secret="client-secret"'
```
