### DISCUSSION TITLE
How to set longer Google OAuth session timeout?

### DISCUSSION THREAD

**Discussion by Haebuk** [kafbat/kafka-ui#950] [Q&A] [answered]
In deployed helm kafbat ui, may be 30 minutes after login, google requires login.
I set the helm values below but not working. 
Is there another method? thank you.

```yaml
replicaCount: 2

yamlApplicationConfig:
  auth:
    type: OAUTH2
    oauth2:
      client:
        google:
          provider: google
          clientId: ...
          clientSecret: ...
          user-name-attribute: email
          custom-params:
            type: google
            allowedDomain: ... # for RBAC
  spring:
    session:
      timeout: 72h

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: balanced
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/session-cookie-name: kafka-ui
  ingressClassName: "nginx"
  host: "..."
```
