### ISSUE TITLE
FE: RBAC problem for broker settings

### ISSUE THREAD

**Issue by fallen-up** [kafbat/kafka-ui#1051]
### Issue submitter TODO list

- [x] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [x] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [x] I've tried running `main`-labeled docker image and the issue still persists there
- [x] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

The broker settings edit buttons are available in the UI, but when you try to do this, the backend ultimately returns a 403 error.

### Your installation details

1.2.0

### Steps to reproduce

role-config (cluster is non-readonly)
```yaml
        permissions:
          - resource: applicationconfig
            actions: ["view"]
          - resource: clusterconfig
            actions: ["view"]

```

### Screenshots

![Image](https://github.com/user-attachments/assets/af48c6e8-1aec-4a3a-a274-f0f3e98593ad)
