### ISSUE TITLE
Consumer Lag Stuck

### ISSUE THREAD

**Issue by Fosol** [kafbat/kafka-ui#1055]
### Issue submitter TODO list

- [x] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [x] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [x] I've tried running `main`-labeled docker image and the issue still persists there
- [x] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

The Consumer Lag never changes, it's stuck.  I've compared the messages with what has been processed in my logs and I've processed all messages.  The consumers are not receiving any new messages.

Is there a way to manually reset the consumer lag, or tell it to recalculate?

This has occurred several times now.  The only fix I've found so far is to delete the topic and consumers.

### Expected behavior

The consumer lag should display the actual lag.  It shouldn't get stuck.  There should be a way to fix this.

### Your installation details

I'm running v1.2.0 in a Podman container.

```yaml
version: '3'
services:
  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:v1.2.0
    profiles:
      - all
    restart: 'always'
    env_file:
      - kafka/kafka-ui/.env
    ports:
      - 8080:8080
    volumes:
      - ./kafka/kafka-ui/config.prod.yaml:/etc/kafkaui/dynamic_config.yaml
```

### Steps to reproduce

I've simply run the container.  I have 6 topics.  The current topic with the bug has 60 partitions, but the bug has occurred randomly to other topics that only have 3 partitions.

### Screenshots

![Image](https://github.com/user-attachments/assets/8eaeeb5d-5e59-450b-8ab5-4886656a02b9)
