### ISSUE TITLE
Pagination is not working

### ISSUE THREAD

**Issue by dhutsj** [kafbat/kafka-ui#1066]
### Issue submitter TODO list

- [x] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [x] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [x] I've tried running `main`-labeled docker image and the issue still persists there
- [x] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

Hello there,

I installed this kafka-ui with the latest version, after that, when I check messages of a topic, all the messages is in a same partition, but the "Next" page button is un-clickable.

Please advise anything I missed. Thank you.

![Image](https://github.com/user-attachments/assets/055cab33-7269-4682-b773-4433d811bd54)

### Expected behavior

The "Next" page button can be click and displays the next offset messages.

### Your installation details

I installed with the latest helm chart with the latest app version.
```shell
helm repo add kafbat-ui https://kafbat.github.io/helm-charts
helm install kafbat-ui kafbat-ui/kafka-ui -f dev_kafka_ui_values.yaml -n kafka-ui
```
Here is the values.yaml
```yaml
yamlApplicationConfig:
  kafka:
    adminClientTimeout: 75000
    clusters:
      - name: dev-msk
        bootstrapServers: xxx
        properties:
          request.timeout.ms: 600000
          security.protocol: SASL_SSL
          sasl.mechanism: SCRAM-SHA-512
          sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required
            username="xxx" password="xxx";
        readOnly: false
  consumer:
    defaultMessagesLimit: 100
    maxPollRecords: 100
    paginationSize: 50
  auth:
    type: disabled
```

### Steps to reproduce

Use this values.yaml to install it, then check the "Next" button in the Messages Page.
