### ISSUE TITLE
RBAC doesn't work (resource: topic)

### ISSUE THREAD

**Issue by fallen-up** [kafbat/kafka-ui#260]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/SECURITY.md)

### Describe the bug (actual behavior)

```yaml
              permissions:
                - resource: applicationconfig
                  actions: [ "view" ]
                - resource: clusterconfig
                  actions: [ "view" ]
                - resource: topic
                  value: ".*"
                  actions: [ "view", "messages_read", "messages_delete" ]
```
don't block "edit" in UI (ghcr.io/kafbat/kafka-ui:v1.0.0)
same config in provectuslabs/kafka-ui:v0.7.1 works properly

### Your installation details

v1.0.0

### Steps to reproduce

enable rbac and use such config:
```yaml
      roles.yml: |
        rbac:
          roles:
            - name: "role-name-ro"
              clusters:
                - cluster-name
              subjects:
                - provider: oauth
                  type: role
                  value: "rolename-ro"
              permissions:
                - resource: applicationconfig
                  actions: [ "view" ]
                - resource: clusterconfig
                  actions: [ "view" ]
                - resource: topic
                  value: ".*"
                  actions: [ "view", "messages_read", "messages_delete" ]
```

### Screenshots

![image](https://github.com/kafbat/kafka-ui/assets/11389898/49eb5097-c4ad-4843-8ee6-9cae89f57f14)
