### ISSUE TITLE
RBAC: Actions granted for cluster A are mistakenly available for cluster B

### ISSUE THREAD

**Issue by smahroug** [kafbat/kafka-ui#274]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

Here the RBAC roles configs :
```
rbac:
  roles:
    - name: "Admin Roles"
      clusters:
        - DEV
        - TST
        - UAT
      subjects:
        - provider: oauth
          type: role
          value: "ADMIN.ROLE.001"
      permissions:
        - resource: clusterconfig
          # value not applicable for clusterconfig
          actions: [ "view" ]
        - resource: topic
          value: ".*"
          actions: all
        - resource: consumer
          value: ".*"
          actions: all
        - resource: schema
          value: ".*"
          actions: all
        - resource: acl
          actions: [view]
    - name: "LAB for ALL"
      clusters:
        - LAB
      subjects:
        - provider: oauth
          type: role
          value: "ADMIN.ROLE.001"
        - provider: oauth
          type: role
          value: "DEV.ROLE.002"
        - provider: oauth
          type: role
          value: "OPS.ROLE.003"
      permissions:
        - resource: clusterconfig
          # value not applicable for clusterconfig
          actions: [ "view" ]
        - resource: topic
          value: ".*"
          actions:
            - VIEW # can be upper or lower case
            - CREATE
            - EDIT
            - DELETE
            - MESSAGES_READ
            - MESSAGES_PRODUCE
            - MESSAGES_DELETE
        - resource: consumer
          value: ".*"
          actions: [ VIEW, DELETE, RESET_OFFSETS ]
        - resource: schema
          value: ".*"
          actions: [ VIEW, CREATE, DELETE, EDIT, MODIFY_GLOBAL_COMPATIBILITY ]
        - resource: acl
          actions: [view, edit]

```
- We have 2 types of permissions : 
Admin Roles where admins can perform actions on 3 clusters ( DEV, TST and UAT)
LAB for All where any user having DEV or OPS or ADMIN role can perform actions on LAB cluster.
-  The identified issue :
All the user were able to create ACL records in LAB and the other environments.

### Expected behavior

All the users should be able to create ACL records only in LAB cluster

### Your installation details

1 - app version : 1.0.0 [2956664]
