### ISSUE TITLE
RBAC: Implement instance-wide default role

### ISSUE THREAD

**Issue by seono** [kafbat/kafka-ui#344]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Hi,
When new kafka consumer gives me a request to approach kafka ui (for readonly),
i have to rewrite rbac yaml file.
I deployed two Kafka UI to solve this problem.
First one has basic authentication is for admin users.
The other one is readonly for kafka consumers.

### Describe the feature you're interested in

I think it is useful if the way i can setup default role is exists.
```yaml
rbac:
  roles:
    - name: "admins"
      clusters:
        - development
      subjects:
         - provider: oauth_github
           type: user
           value: 'seono'
      permissions:
        ...
    - name: "readonly"
      clusters:
        - development
      subjects:
        - provider: oauth_github
          type: default
      permissions:
        ...
```

### Describe alternatives you've considered

I know there is other type `organization` and `team`.
If someone wants readonly permission, I can invite them to the group.
But.. In my case, my company has too many organzations and teams so i can not use it properly.

### Version you're running

https://github.com/kafbat/kafka-ui/commit/9843ee0
