### ISSUE TITLE
Readonly roles can create acls

### ISSUE THREAD

**Issue by marcosschroh** [kafbat/kafka-ui#370]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

When using RBAC with a readonly role it is possible to create ACLs, which I think it should not be allowed

### Expected behavior

Read only roles should not be able to create ACLs.

### Your installation details

```yaml

# values.yaml
kafka-ui:
  # kubernetes resources
  image:
    repository: kafbat/kafka-ui
    tag: "v1.0.0"

# Chart.yaml
dependencies:
- name: kafka-ui
  version: "1.4.0"
  repository: "https://kafbat.github.io/helm-charts"
```

### Steps to reproduce

Setup RBAC and use the configuration that is it found in the [documentation](https://ui.docs.kafbat.io/configuration/rbac-role-based-access-control#example-file)

```yaml
rbac:
  roles:
    - name: "readonly"
      clusters:
        # FILL THIS
      subjects:
        # FILL THIS
      permissions:
        - resource: clusterconfig
          actions: [ "view" ]

        - resource: topic
          value: ".*"
          actions: 
            - VIEW
            - MESSAGES_READ

        - resource: consumer
          value: ".*"
          actions: [ view ]

        - resource: schema
          value: ".*"
          actions: [ view ]

        - resource: connect
          value: ".*"
          actions: [ view ]

```

### Screenshots

![Screenshot 2024-05-06 at 16 30 36](https://github.com/kafbat/kafka-ui/assets/2828842/b13b7edc-ec6c-48f0-bd00-9d398f5cccb6)
![Screenshot 2024-05-06 at 16 32 38](https://github.com/kafbat/kafka-ui/assets/2828842/fab74843-d6b7-43b3-a7b2-5c218e4fb918)
