### ISSUE TITLE
Content NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by vicziani** [kafbat/kafka-ui#476]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

I'am using the Apicurio Schema Registry. After I create a JSON schema and try to send a message, I get the following error message:

`Content NOT SUPPORTED: keyword "id", use "$id" for schema ID`

JSON Schema:

```json
{
  "$id": "https://training.com/EmployeeHasBeenCreatedEvent.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "EmployeeHasBeenCreatedEvent",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64",
      "description": "The employee's id."
    },
    "name": {
      "type": "string",
      "minLength": 1,
      "description": "The employee's name."
    }
  }
}
```

Reading messages based on the schema works well.

### Expected behavior

Send the message.

### Your installation details

Same with v1.0.0 and 4de0d53.

```yaml
  schema-registry:
    image: apicurio/apicurio-registry-mem:2.6.1.Final
    ports: 
      - "8081:8080"
  kafka-ui:
    #image: ghcr.io/kafbat/kafka-ui:v1.0.0
    image: ghcr.io/kafbat/kafka-ui:4de0d5330d0c615e70fd9693bba265e6536029e9
    depends_on:
      - kafka
      - schema-registry
    ports:
      - 8082:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://schema-registry:8080/apis/ccompat/v7
      - DYNAMIC_CONFIG_ENABLED='true'
```

### Steps to reproduce

1. Create schema
2. Create topic
3. Send message

### Screenshots

![image](https://github.com/kafbat/kafka-ui/assets/1205411/a2d3e4af-eafa-49c6-bac0-ae3725b0e1e0)
![image](https://github.com/kafbat/kafka-ui/assets/1205411/d188beae-3e66-49e2-be22-cf89b45853eb)
![image](https://github.com/kafbat/kafka-ui/assets/1205411/cb3a88b5-52c7-4795-b9a8-b6445a07e3b8)

The JSON is generated by Kafka UI.

### Logs

Nothing appears in the log.
