### ISSUE TITLE
BE: Make gh version check timeout configurable

### ISSUE THREAD

**Issue by eroji** [kafbat/kafka-ui#477]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

I tried to run the lastest v1.0.0 kafbat-ui in both standalone Docker and in Kubernetes. When running standalone, the UI looks fine, but when running in Kubernetes as a deployment, the UI shows this.

![image](https://github.com/user-attachments/assets/ec52a93e-40dd-4179-b13e-8df20131b2a0)

### Expected behavior

The application should be able to find what the latest version is and not indicate that it is outdated.

### Your installation details

See my attached screenshot. The application is deployed as a deployment, with some modifications done to the Helm version, but none of which should prevent it from checking for the latest version.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-ui
      app.kubernetes.io/instance: kafka-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-ui
        app.kubernetes.io/instance: kafka-ui
    spec:
      serviceAccountName: kafka-ui
      containers:
      - name: kafka-ui-pod
        image: ghcr.io/kafbat/kafka-ui:v1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: AUTH_TYPE
          value: "LOGIN_FORM"
        - name: SPRING_SECURITY_USER_NAME
          value: "admin"
        - name: SPRING_SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-ui-secret
              key: password
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 45
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 45
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 200Mi
        volumeMounts:
        - name: config
          mountPath: /etc/kafkaui/config.yaml
          subPath: config.yaml
      volumes:
      - name: config
        configMap:
          name: kafka-ui-configmap
```

### Steps to reproduce

Deploy the above manifest inside a Kubernetes cluster.

### Screenshots

![image](https://github.com/user-attachments/assets/bcc75d4b-0594-46f5-b235-d2bdadb18cdf)
