### ISSUE TITLE
I like to implement RBAC with okta but got below error, can someone kindly help me with this ? the app loads fine if I do not use RBAC configurations.

### ISSUE THREAD

**Issue by ragavse** [kafbat/kafka-ui#493]
I like to implement RBAC with okta but got below error, can someone kindly help me with this ? the app loads fine if I do not use RBAC configurations. 

When I preview the token with okta admin, I see claims are added only to the id_token and not in access token. could this be a reason ?

LOGS:
`[30m2024-07-22 20:07:23,417[0;39m [39mDEBUG[0;39m [[34mreactor-http-epoll-3[0;39m] [33mi.k.u.s.r.e.OauthAuthorityExtractor[0;39m: Param missing from attributes, skipping`

yaml Configurations:

```
yamlApplicationConfig:
  kafka:
    clusters:
      - name: <<ClusterName>
        bootstrapServers: <<Broker url>>
        properties:
          security.protocol: SASL_SSL
          sasl.mechanism: AWS_MSK_IAM
          sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
          sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
  auth:
    type: OAUTH2
    oauth2:
      client:
        okta:
          clientId:
          clientSecret:
          scope: [ 'openid', 'profile', 'email', 'groups' ]
          client-name: Okta
          provider: okta
          redirect-uri: http://<< internal >>/login/oauth2/code/okta
          authorization-grant-type: authorization_code
          issuer-uri: https://<< internal >>.oktapreview.com
          jwk-set-uri: https://<< internal >>.oktapreview.com/oauth2/v1/keys?client_id=<< Client id >>
          user-name-attribute: email
          custom-params:
            type: oauth
            roles-field: groups
  rbac:
    roles:
      - name: "Editors"
        clusters:
          - <<ClusterName>
        subjects:
          - provider: oauth
            type: role
            value: "Editors"
        permissions:
          - resource: topic
            value: ".*"
            actions:
              - VIEW
              - MESSAGES_READ
              - EDIT
              - CREATE
              - EDIT
              - MESSAGES_PRODUCE
```

Result:
<img width="1174" alt="Screenshot 2024-07-22 at 4 28 37 PM" src="https://github.com/user-attachments/assets/63f45c61-b694-437f-ba3f-dfbb7d04463e">

Okta Groups claim:

<img width="709" alt="Screenshot 2024-07-22 at 4 38 22 PM" src="https://github.com/user-attachments/assets/78b872ef-75e1-4a7e-8a27-9c603a9973c6">

_Originally posted by @ragavse in https://github.com/kafbat/kafka-ui/discussions/491_
