### ISSUE TITLE
BE: Support self-signed certs for OIDC

### ISSUE THREAD

**Issue by Haarolean** [kafbat/kafka-ui#615]
Currently to achieve this one has to do mental gymnastics like this:
```
JAVA_OPTS: >-
        -Djavax.net.ssl.trustStore=/jmx/clienttruststore
        -Djavax.net.ssl.trustStorePassword=12345678
```

This happened due to:
1) unifying truststore/keystore usage per cluster
2) with 1) having no universal truststore/keystore applicable to non-clustered things (authentication, etc)

TODO:
1) Implement an app-wide truststore/keystore support
2) Use it for accessing:
- OIDC endpoints
- ?

**Comment by Haarolean** [comment]
Seems to be solvable via these config props:
```
server:
  ssl:
    trust-store: classpath:keycloak-truststore.jks
    trust-store-password: changeit
```

Documented [here](https://ui.docs.kafbat.io/faq/faq), closing.
